// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcNbrGegwU8Ld57Sep_-fXS9NmY6epazM',
    appId: '1:748695665005:web:9462279bca3215f5ba8264',
    messagingSenderId: '748695665005',
    projectId: 'real-time-database-16636',
    authDomain: 'real-time-database-16636.firebaseapp.com',
    storageBucket: 'real-time-database-16636.appspot.com',
    measurementId: 'G-91F6QHSZF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzWBHOCBMUEp93WxuXdM6LOOc5N-UJwVg',
    appId: '1:748695665005:android:d48aee191eace1bcba8264',
    messagingSenderId: '748695665005',
    projectId: 'real-time-database-16636',
    storageBucket: 'real-time-database-16636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBba7nEImYJD7_RLn0hJ4wLFtK46mEd9Jo',
    appId: '1:748695665005:ios:530331fc427ba044ba8264',
    messagingSenderId: '748695665005',
    projectId: 'real-time-database-16636',
    storageBucket: 'real-time-database-16636.appspot.com',
    iosClientId: '748695665005-gjhvpg2f6pnq7usr5taem8ikdh4rjesg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRealtimeDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBba7nEImYJD7_RLn0hJ4wLFtK46mEd9Jo',
    appId: '1:748695665005:ios:530331fc427ba044ba8264',
    messagingSenderId: '748695665005',
    projectId: 'real-time-database-16636',
    storageBucket: 'real-time-database-16636.appspot.com',
    iosClientId: '748695665005-gjhvpg2f6pnq7usr5taem8ikdh4rjesg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRealtimeDb',
  );
}
